#%RAML 0.8
title: "Sample-Module"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v1

documentation:
  - title: mod-orders (Acquisition Method)
    content: <b>CRUD APIs used to manage acquisition methods.</b>

schemas:
  - acquisition_method.json: !include acq-models/mod-orders-storage/schemas/acquisition_method.json
  - acquisition_method_collection: !include acq-models/mod-orders-storage/schemas/acquisition_method_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/acquisition_method:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/acquisition_method_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/acquisition_method_post.sample
      schemaCollection: acquisition_method_collection
      schemaItem: acquisition_method.json
  get:
    description: Get list of acquisition_methods
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/acquisition_method_post.sample
        schema: acquisition_method.json
