#%RAML 1.0
title: "Orders Storage"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v1

documentation:
  - title: Acquisitions units
    content: <b>CRUD APIs used to manage acquisitions units.</b>

types:
    acquisitions-unit: !include acq-models/mod-orders-storage/schemas/acquisitions_unit.json
    acquisitions-unit-collection: !include acq-models/mod-orders-storage/schemas/acquisitions_unit_collection.json
    UUID:
     type: string
     pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/acquisitions-unit-storage/units:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/acquisitions_unit_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/acquisitions_unit_post.sample
      schemaCollection: acquisitions-unit-collection
      schemaItem: acquisitions-unit
  get:
    description: Get list of relationships
    is: [
      searchable: {description: "with valid searchable fields: for example protectRead", example: "[\"protectRead\", \"false\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a acquisitions unit
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/acquisitions_unit_post.sample
        schema: acquisitions-unit
