#%RAML 0.8
title: "Sample-Module"
baseUri: http://github.com/folio-org/mod-orders
version: v1

documentation:
  - title: mod-orders (Activation Status)
    content: <b>CRUD APIs used to manage activation statuses.</b>

schemas:
  - activation_status.json: !include acq-models/mod-orders-storage/schemas/activation_status.json
  - activation_status_collection: !include acq-models/mod-orders-storage/schemas/activation_status_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/activation_status:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/activation_status_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/activation_status_post.sample
      schemaCollection: activation_status_collection
      schemaItem: activation_status.json
  get:
    description: Get list of acquisition_methods
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/activation_status_post.sample
        schema: activation_status.json