#%RAML 0.8
title: "Orders-Module"
baseUri: http://github.com/folio-org/mod-orders
version: v1

documentation:
  - title: mod-orders (Adjustment)
    content: <b>CRUD APIs used to manage adjustments.</b>

schemas:
  - changelog: !include schemas/changelog.json
  - adjustment.json: !include schemas/adjustment.json
  - adjustment_collection: !include schemas/adjustment_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/adjustment:
  type:
    collection:
      exampleCollection: !include examples/adjustment_collection.sample
      exampleItem: !include examples/adjustment_get.sample
      schemaCollection: adjustment_collection
      schemaItem: adjustment.json
  get:
    description: Get list of alerts
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/adjustment_get.sample
        schema: adjustment.json