#%RAML 0.8
title: "Sample-Module"
baseUri: http://github.com/folio-org/mod-orders
version: v1

documentation:
  - title: mod-orders (Alert)
    content: <b>CRUD APIs used to manage alerts.</b>

schemas:
  - changelog: !include schemas/changelog.json
  - alert.json: !include schemas/alert.json
  - alert_collection.json: !include schemas/alert_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/alert:
  type:
    collection:
      exampleCollection: !include examples/alert_collection.sample
      exampleItem: !include examples/alert_post.sample
      schemaCollection: alert_collection.json
      schemaItem: alert.json
  get:
    description: Get list of alerts
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
  /{alert_id}:
    type:
      collection-item:
        exampleItem: !include examples/alert_get.sample
        schema: alert.json