#%RAML 1.0
title: "Orders Storage"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v1

documentation:
  - title: mod-orders (Alert)
    content: <b>CRUD APIs used to manage alerts.</b>

types:
    alert: !include acq-models/mod-orders-storage/schemas/alert.json
    alert_collection: !include acq-models/mod-orders-storage/schemas/alert_collection.json
    UUID:
     type: string
     pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/alert:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/alert_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/alert_post.sample
      schemaCollection: alert_collection
      schemaItem: alert
  get:
    description: Get list of alerts
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a Alert
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/alert_post.sample
        schema: alert
