#%RAML 1.0
title: "mod-orders-storage"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v1.0

documentation:
  - title: Bind Item Piece
    content: <b>This module implements the CRUD interface for Bind Item Piece records. </b>

types:
  bind-piece-item: !include acq-models/mod-orders-storage/schemas/bind_piece_item.json
  bind-piece-item-collection: !include acq-models/mod-orders-storage/schemas/bind_piece_item_collection.json
  error: !include raml-util/schemas/error.schema
  errors: !include raml-util/schemas/errors.schema
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  orderable: !include raml-util/traits/orderable.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/orders-storage/bind-piece-items:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/bind_piece_item_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/bind_piece_item_get.sample
      schemaCollection: bind-piece-item-collection
      schemaItem: bind-piece-item
  get:
    description: Get collection of BindItemPiece objects
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"itemId\", \"ae863930-5e50-4d5d-ba3d-61609248d617\", \"=\"]"},
      pageable
    ]
  post:
    description: Create a new bind piece item record
    is: [validate]
  /{id}:
    uriParameters:
      id:
        description: The UUID of Bind Piece Item object
        type: UUID
    description: Get, Delete or Update a specific bind piece item
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/bind_piece_item_get.sample
        schema: bind-piece-item
