#%RAML 1.0
title: "Orders Storage"
baseUri: http://github.com/org/folio/mod-orders-storage
version: v1

documentation:
  - title: Cost
    content: <b>CRUD API</b>

types:
    cost: !include acq-models/mod-orders-storage/schemas/cost.json
    cost_collection: !include acq-models/mod-orders-storage/schemas/cost_collection.json
    UUID:
     type: string
     pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/cost:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/cost_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/cost_post.sample
      schemaCollection: cost_collection
      schemaItem: cost
  get:
    description: Get list of costs
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a Cost
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/cost_get.sample
        schema: cost
