#%RAML 0.8
title: "Sample-Module"
baseUri: http://github.com/org/folio/sample-module
version: v1

documentation:
  - title: Sample Module
    content: <b>CRUD API</b>

schemas:
  - cost.json: !include schemas/cost.json
  - cost_collection: !include schemas/cost_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/cost:
  type:
    collection:
      exampleCollection: !include examples/cost_collection.sample
      exampleItem: !include examples/cost_post.sample
      schemaCollection: cost_collection
      schemaItem: cost.json
  get:
    description: Get list of alerts
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/cost_get.sample
        schema: cost.json