#%RAML 0.8
title: "Sample-Module"
baseUri: http://github.com/org/folio/sample-module
version: v1

documentation:
  - title: Sample Module
    content: <b>CRUD API</b>

schemas:
  - changelog: !include schemas/changelog.json
  - fund_distribution: !include schemas/po_line_fund_distribution.json
  - cost_collection: !include schemas/po_line_fund_distribution_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/fund_distribution:
  type:
    collection:
      exampleCollection: !include examples/fund_distribution_collection.sample
      exampleItem: !include examples/fund_distribution_post.sample
      schemaCollection: fund_distribution_collection
      schemaItem: po_line_fund_distribution.json
  get:
    description: Get list of fund_distributions
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
  /{fund_distribution_id}:
    type:
      collection-item:
        exampleItem: !include examples/fund_distribution_get.sample
        schema: po_line_fund_distribution.json