#%RAML 1.0
title: "Sample-Module"
baseUri: http://github.com/org/folio/sample-module
version: v1

documentation:
  - title: Sample Module
    content: <b>CRUD API</b>

types:
    location: !include acq-models/mod-orders-storage/schemas/location.json
    location_collection: !include acq-models/mod-orders-storage/schemas/location_collection.json

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/location:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/location_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/location_post.sample
      schemaCollection: location_collection
      schemaItem: location
  get:
    description: Get list of locations
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/location_get.sample
        type: location
