#%RAML 1.0
title: "mod-orders-storage"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v2

documentation:
  - title: Orders
    content: <b>Get list of purchase orders API.  This API is intended for internal use only.  Please use the /orders/composite-orders API provided by mod-orders instead.</b>

types:
    purchase_order: !include acq-models/mod-orders-storage/schemas/purchase_order.json
    purchase_order_collection: !include acq-models/mod-orders-storage/schemas/purchase_order_collection.json

traits:
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection-get: !include raml-util/rtypes/collection-get.raml

/orders:
  type:
    collection-get:
      exampleCollection: !include acq-models/mod-orders-storage/examples/purchase_order_collection.sample
      schemaCollection: purchase_order_collection
  get:
    description: Get list of purchase orders
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
