#%RAML 0.8
title: "Sample-Module"
baseUri: http://github.com/org/folio/sample-module
version: v1

documentation:
  - title: Sample Module
    content: <b>CRUD API</b>

schemas:
  - order_type.json: !include schemas/order_type.json
  - order_type_collection: !include schemas/order_type_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/order_type:
  type:
    collection:
      exampleCollection: !include examples/order_type_collection.sample
      exampleItem: !include examples/order_type_post.sample
      schemaCollection: order_type_collection
      schemaItem: order_type.json
  get:
    description: Get list of order_types
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/order_type_get.sample
        schema: order_type.json