#%RAML 1.0
title: "mod-orders-storage"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v3.1

documentation:
  - title: Order-lines
    content: <b>API to get list of po lines by quering a view combining purchase_orders,po_lines. This API is intended for internal use only.  Please use the /orders/order-lines API provided by mod-orders instead.</b>

types:
    po_line_collection: !include acq-models/mod-orders-storage/schemas/po_line_collection.json

traits:
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection-get: !include raml-util/rtypes/collection-get.raml

/orders-storage/order-lines:
  type:
    collection-get:
      exampleCollection: !include acq-models/mod-orders-storage/examples/po_line_collection.sample
      schemaCollection: po_line_collection
  get:
    description: Get list of po lines matching a query that can contain fields from purchase_order or/and po_line
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
