#%RAML 1.0
title: "mod-orders"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v9.3

documentation:
  - title: PO Line
    content: <b>This module implements the CRUD interface.  This API is intended for internal use only.  Please use the /orders/order-lines API provided by mod-orders instead.</b>

types:
  po-line-collection: !include acq-models/mod-orders-storage/schemas/po_line_collection.json
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
traits:


/orders-storage/po-lines-batch:
  displayName: Finance release encumbrance
  description: Finance release encumbrance APIs
  put:
    description: "asd"
    body:
      application/json:
        type: po-line-collection
        example:
          strict: false
          value: !include acq-models/mod-orders-storage/examples/po_line_collection.sample
    responses:
      204:
        description: "Item successfully updated"
      404:
        description: "Item with a given ID not found"
        body:
          text/plain:
            example: "Bad request"
      400:
        description: "Bad request, e.g. malformed request body or query parameter. Details of the error (e.g. name of the parameter or line/character number with malformed data) provided in the response."
        body:
          text/plain:
            example: "unable to update <<resourcePathName|!singularize>> -- malformed JSON at 13:4"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "internal server error, contact administrator"


