#%RAML 1.0
title: "mod-orders"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v9.3

documentation:
  - title: PO Line
    content: <b>This module implements the CRUD interface.  This API is intended for internal use only.  Please use the /orders/order-lines API provided by mod-orders instead.</b>

types:
    po-line: !include acq-models/mod-orders-storage/schemas/po_line.json
    po-line-collection: !include acq-models/mod-orders-storage/schemas/po_line_collection.json
    create-inventory-type: !include acq-models/mod-orders/schemas/createInventoryType.json
    order-line-patch-operation-type: !include acq-models/mod-orders/schemas/patch_order_line_operation_type.json
    storage-patch-order-line-request: !include acq-models/mod-orders-storage/schemas/storage_patch_order_line_request.json
    storage-replace-order-line-instance: !include acq-models/mod-orders-storage/schemas/storage_replace_order_line_instance_ref.json
    order-line-audit-event: !include acq-models/mod-orders-storage/schemas/order_line_audit_event.json
    UUID:
     type: string
     pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/orders-storage/po-lines:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/po_line_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/po_line_get.sample
      schemaCollection: po-line-collection
      schemaItem: po-line
  get:
    description: Get list of po lines
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a PO Line
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/po_line_get.sample
        schema: po-line
    patch:
      description: Apply partial modifications to a order line
      body:
        application/json:
          description: Storage patch request
          type: storage-patch-order-line-request
          example:
            strict: false
            value: !include acq-models/mod-orders-storage/examples/storage_patch_order_line_request.sample
      responses:
        204:
          description: Successful modifications
        404:
          description: No content
        500:
          description: Error
