#%RAML 1.0
title: "mod-orders"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v9.3

documentation:
  - title: PO Line batch
    content: <b>This module implements the PO lines batch processing interface.  This API is intended for internal use only.

types:
  po-line-collection: !include acq-models/mod-orders-storage/schemas/po_line_collection.json
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

# workaround to prevent api-lint errors for FQM vendor extensions
# see https://github.com/folio-org/fqm-tools/blob/main/docs/generation/field-schema.md#raml-validation-errors
annotationTypes:
  fqm-essential:
    type: boolean
  fqm-visibility:
    type: string
  fqm-visible-by-default:
    type: boolean

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
traits:


/orders-storage/po-lines-batch:
  displayName: Process list of PO lines in a batch
  description: Process list of PO lines in a batch APIs
  put:
    description: "Update the list of PO lines in a batch"
    body:
      application/json:
        type: po-line-collection
        example:
          strict: false
          value: !include acq-models/mod-orders-storage/examples/po_line_collection.sample
    responses:
      204:
        description: "Collection successfully updated"
      400:
        description: "Bad request, e.g. malformed request body or query parameter. Details of the error (e.g. name of the parameter or line/character number with malformed data) provided in the response."
        body:
          text/plain:
            example: "unable to update <<resourcePathName|!singularize>> -- malformed JSON at 13:4"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "internal server error, contact administrator"
