#%RAML 0.8
title: "mod-orders"
baseUri: http://github.com/folio-org/mod-orders
version: v1

documentation:
  - title: mod-orders
    content: <b>This module implements the CRUD interface</b>

schemas:
  - po_line.json: !include schemas/po_line.json
  - po_line_collection: !include schemas/po_line_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/po_line:
  type:
    collection:
      exampleCollection: !include examples/po_line_collection.sample
      exampleItem: !include examples/po_line_post.sample
      schemaCollection: po_line_collection
      schemaItem: po_line.json
  get:
    description: Get list of purchase orders
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/po_line_post.sample
        schema: po_line.json

