#%RAML 0.8
title: "Sample-Module"
baseUri: http://github.com/org/folio/sample-module
version: v1

documentation:
  - title: Sample Module
    content: <b>CRUD API</b>

schemas:
  - po_line.json: !include schemas/po_line.json
  - adjustment.json: !include schemas/adjustment.json
  - alert.json: !include schemas/alert.json
  - claim.json: !include schemas/claim.json
  - cost.json: !include schemas/cost.json
  - details.json: !include schemas/details.json
  - eresource.json: !include schemas/eresource.json
  - fund_distribution.json: !include schemas/fund_distribution.json
  - license.json: !include schemas/license.json
  - location.json: !include schemas/location.json
  - order_format.json: !include schemas/order_format.json
  - order_type.json: !include schemas/order_type.json
  - physical.json: !include schemas/physical.json
  - receipt_status.json: !include schemas/receipt_status.json
  - renewal.json: !include schemas/renewal.json
  - source.json: !include schemas/source.json
  - vendor.json: !include schemas/vendor.json
  - workflow_status.json: !include schemas/workflow_status.json
  - po_line_collection.json !include schemas/po_line_collection.json


traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/po_line:
  
  get:
    description: Get list of po_lines
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
  /{po_line_id}:
    type:
      collection-item:
        exampleItem: !include examples/po_line_get.sample
        schema: po_line.json
