#%RAML 0.8
title: "Sample-Module"
baseUri: http://github.com/org/folio/sample-module
version: v1

documentation:
  - title: Sample Module
    content: <b>CRUD API</b>

schemas:
  - changelog: !include schemas/changelog.json
  - po_line: !include schemas/po_line.json
  - po_line_adjustment: !include schemas/po_line_adjustment.json
  - po_line_alert: !include schemas/po_line_alert.json
  - po_line_claim: !include schemas/po_line_claim.json
  - po_line_collection !include schemas/po_line_collection.json
  - po_line_cost: !include schemas/po_line_cost.json
  - po_line_detials: !include schemas/po_line_details.json
  - po_line_eresource: !include schemas/po_line_eresource.json
  - po_line_fund_distribution: !include schemas/po_line_fund_distribution.json
  - po_line_license: !include schemas/po_line_license.json
  - po_line_location: !include schemas/po_line_location.
  - po_line_order_format: !include schemas/po_line_order_format.json
  - po_line_order_type: !include schemas/po_line_order_type.json
  - po_line_physical: !include schemas/po_line_physical.json
  - po_line_receipt_status: !include schemas/po_line_receipt_status.json
  - po_line_renewal: !include schemas/po_line_renewal.json
  - po_line_source: !include schemas/po_line_source.json
  - po_line_vendor: !include schemas/po_line_vendor.json
  - po_line_workflow_status: !include schemas/po_line_workflow_status.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/po_line:
  type:
    collection:
      exampleCollection: !include examples/po_line_collection.sample
      exampleItem: !include examples/po_line_post.sample
      schemaCollection: po_line_collection
      schemaItem: po_line.json
  get:
    description: Get list of po_lines
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
  /{po_line_id}:
    type:
      collection-item:
        exampleItem: !include examples/po_line_get.sample
        schema: po_line.json
