#%RAML 1.0
title: "Orders Storage"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v2

documentation:
  - title: Purchase Order Number
    content: <b>API used to manage PO number.</b>

types:
  po-number: !include acq-models/mod-orders-storage/schemas/sequence_number.json

traits:
    language: !include raml-util/traits/language.raml

/orders-storage/po-number:
  get:
    is: [language]
    description: Get generated purchase order number
    responses:
      200:
        body:
          application/json:
            type: po-number
      400:
        description: "Bad request, e.g. malformed request body or query parameter"
        body:
          text/plain:
            example: "Unable to generate purchase order number"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "internal server error, contact administrator"
