#%RAML 1.0
title: "mod-orders-storage"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v2

documentation:
  - title: Purchase Order
    content: <b>This module implements the CRUD interface</b>

types:
    purchase-order: !include acq-models/mod-orders-storage/schemas/purchase_order.json
    purchase-order-collection: !include acq-models/mod-orders-storage/schemas/purchase_order_collection.json
    UUID:
     type: string
     pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/orders-storage/purchase-orders:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/purchase_order_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/purchase_order_get.sample
      schemaCollection: purchase-order-collection
      schemaItem: purchase-order
  get:
    description: Get list of purchase orders
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a Purchase Order
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/purchase_order_get.sample
        schema: purchase-order
