#%RAML 1.0
title: "mod-orders-storage"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v3

documentation:
  - title: Receiving History
    content: <b>Get list of receiving history API.  This API is intended for internal use only.  Please use the /orders/receiving-history API provided by mod-orders instead.</b>

types:
    receiving-history: !include acq-models/mod-orders-storage/schemas/receiving_history.json
    receiving-history-collection: !include acq-models/mod-orders-storage/schemas/receiving_history_collection.json

traits:
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection-get: !include raml-util/rtypes/collection-get.raml

/orders-storage/receiving-history:
  type:
    collection-get:
      exampleCollection: !include acq-models/mod-orders-storage/examples/receiving_history_collection.sample
      schemaCollection: receiving-history-collection
  get:
    description: Get list of receiving history
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
