#%RAML 1.0
title: "Sample-Module"
baseUri: http://github.com/org/folio/sample-module
version: v1

documentation:
  - title: mod-orders (Reporting Code)
    content: <b>CRUD APIs used to manage reporting codes.</b>

types:
    reporting_code: !include acq-models/mod-orders-storage/schemas/reporting_code.json
    reporting_code_collection: !include acq-models/mod-orders-storage/schemas/reporting_code_collection.json

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/reporting_code:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/reporting_code_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/reporting_code_post.sample
      schemaCollection: reporting_code_collection
      schemaItem: reporting_code
  get:
    description: Get list of renewals
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/reporting_code_post.sample
        type: reporting_code
