#%RAML 0.8
title: "Sample-Module"
baseUri: http://github.com/org/folio/sample-module
version: v1

documentation:
  - title: Sample Module
    content: <b>CRUD API</b>

schemas:
  - reporting_code.json: !include schemas/eporting_code.json
  - eporting_code_collection: !include schemas/eporting_code_collection.json

traits:
  - secured: !include raml-util/traits/auth.raml
  - orderable: !include raml-util/traits/orderable.raml
  - pageable:  !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml

/eporting_code:
  type:
    collection:
      exampleCollection: !include examples/renewal_collection.sample
      exampleItem: !include examples/renewal_post.sample
      schemaCollection: eporting_code
      schemaItem: eporting_code.json
  get:
    description: Get list of renewals
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    type:
      collection-item:
        exampleItem: !include examples/eporting_code_post.sample
        schema: eporting_code.json