#%RAML 1.0
title: "Orders Storage"
baseUri: http://github.com/org/folio/mod-orders-storage
version: v1

documentation:
  - title: Reporting Code
    content: <b>CRUD APIs used to manage reporting codes.</b>

types:
    reporting_code: !include acq-models/mod-orders-storage/schemas/reporting_code.json
    reporting_code_collection: !include acq-models/mod-orders-storage/schemas/reporting_code_collection.json
    UUID:
     type: string
     pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/reporting_code:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/reporting_code_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/reporting_code_post.sample
      schemaCollection: reporting_code_collection
      schemaItem: reporting_code
  get:
    description: Get list of renewals
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a Reporting Code
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/reporting_code_post.sample
        schema: reporting_code
