#%RAML 1.0
title: "mod-orders-storage"
baseUri: http://github.com/folio-org/mod-orders-storage
version: v9.3

documentation:
  - title: Routing List
    content: <b>This module implements the CRUD interface. This API is intended for internal use only. </b>

types:
    routing-list: !include acq-models/mod-orders-storage/schemas/routing_list.json
    routing-list-collection: !include acq-models/mod-orders-storage/schemas/routing_list_collection.json
    errors: !include raml-util/schemas/errors.schema
    UUID:
     type: string
     pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable: !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    validate: !include raml-util/traits/validation.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/orders-storage/routing-lists:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orders-storage/examples/routing_list_collection.sample
      exampleItem: !include acq-models/mod-orders-storage/examples/routing_list_get.sample
      schemaCollection: routing-list-collection
      schemaItem: routing-list
  get:
    description: Get collection of routing lists
    is: [
      searchable: { description: "CQL query", example: "name=MyRoutingList" },
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a Routing List
        type: UUID
    displayName: Routing List
    description: Get, Delete or Update a specific routing list
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orders-storage/examples/routing_list_get.sample
        schema: routing-list

